# scan_to_scan_filter_chain:
/**:
  ros__parameters:
    filter1:
      name: angle_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -0.58
        upper_angle: 0.58
    filter2:
      name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.0
        upper_threshold: 4.5
        lower_replacement_value: 0.0
        upper_replacement_value: 4.5
    filter3:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: mvibot/base_link # $(arg mvibot_seri)/base_footprint
        min_x: -0.705
        max_x: 0.65
        min_y: -0.285
        max_y: 0.285
        min_z: -1.0
        max_z: 1.0
        invert: false
