/**:
  ros__parameters:
    video_device: "/dev/video12"
    framerate: 25.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb"
    av_device_format: "YUV422P"
    image_width: 1280
    image_height: 720
    camera_name: "camera"
    camera_info_url: "file:///home/mvibot/floorCleaningRobot_ws/src/lower_layer_mvibot/param/camera_info.yaml"
    brightness: 0
    contrast: 32
    saturation: 64
    sharpness: 3
    gain: 0
    auto_white_balance: true
    white_balance: 4600
    autoexposure: true
    exposure: 157
    autofocus: false
    focus: 420
